### ISSUE TITLE
Reset Base Margins and Other Styles

### ISSUE THREAD

**Issue by johndjameson** [spellbook/css#1]
In the current version of Spellbook CSS, we include styles on base tags (`p`, `ul`, `li`, `a`, etc.).

I think we avoid adding those and, instead, reset base styles completely. That means no margins and base elements inherit other properties (`font-size`, `color`, etc.).

This makes for better semantics because we can use the most appropriate tag in any context without worrying about the styles. Like using `h3.sb-heading.sb-heading--2`, but for other elements too.

I’m mostly trying to target `p` tags here. Look at most of our code and you’ll see `mbf` is used more than any other tool class — mostly on `p` elements. We assume `p` elements are stacked atop each other in longform text, so we’ve historically given them a bottom margin. They’re really only stacked a minority of the time though, and we could handle that spacing through modifiers, tools, or a `list`-like module.

It’s a little tedious, but adding explicit classes lets us _find_ and _maintain_ base tags as well.

**Comment by johndjameson** [comment]
Here’s what that looks like on JavaScript.com: https://github.com/codeschool/JavaScript.com/blob/master/client/stylesheets/spellbook/_1_reset.scss

**Comment by drewbarontini** [comment]
To add to the example, I think a `sb-longform` or `sb-content` module would be perfect for styling blocks of content where `p`s are stacked.
