### ISSUE TITLE
Move Variables into Module Files

### ISSUE THREAD

**Issue by johndjameson** [spellbook/css#3]
We agreed on this a while back, but never documented it anywhere.

Moving variables into the files make them easier to add while working and maintain later on, but it can cause issues when requiring variables _across_ modules. We do that in a few places in `config.scss` in production projects. But to keep things portable, it’s probably a better idea to create a global variable and override the `default` inside both modules files.

Something to be aware of, but the tradeoff is worth it for the workflow boost and the ability to more easily copy modules across from the Library and other projects.

**Comment by drewbarontini** [comment]
Yeah, if you were to need a module-level variable in another module, then it should become a higher-level variable they both pull from. We just need a convention for where that goes.

**Comment by dandenney** [comment]
This is my favorite thing, ever.

**Comment by drewbarontini** [comment]
Updated in the core, but this is more just a general convention that we'll have to document.
