### ISSUE TITLE
Split Tools into Individual Files

### ISSUE THREAD

**Issue by johndjameson** [spellbook/css#4]
I’ve think we have a convention for this on large projects, but I think it makes sense as the default. It’s a lot quicker to find the file by name when searching `toolsborder` than it is to open the `tools` file and find the `border` section.

For properties like `margin` that are split into multiple properties (`margin-bottom`, etc.), we can include those in a single file. Or maybe not. I split the `font` ones out, which is inconsistent.

Here’s what that looks like on the JS.com [repo](https://github.com/codeschool/JavaScript.com/tree/master/client/stylesheets/spellbook/tools).

**Comment by drewbarontini** [comment]
I prefer to just have `margin` in one file, `font` in one file, `flex` in one file, etc.

**Comment by johndjameson** [comment]
Met and agreed to split tools out into prewritten files with conditional blocks.

**Comment by johndjameson** [comment]
Going to simplify my approach here and use the aforementioned conditional blocks instead of tool automation.

Dumb is smart 👌
