### ISSUE TITLE
Change Tools to Resemble CSS Properties

### ISSUE THREAD

**Issue by johndjameson** [spellbook/css#5]
So `sb-tci` and `sb-tfh` would become `sb-ci` and `sb-ffh`, like `color` and `font-family`.

I think we mentioned doing `sb-c-invert` and `sb-ff-heading` at some point. Refresh my memory.

**Comment by drewbarontini** [comment]
Yeah, I'm personally a fan of `sb-c-invert` and `sb-ff-heading`. Yes, it's more verbose, but the convention is better because `-invert` and `-heading` are _modifiers_ in this case, if you will.

**Comment by johndjameson** [comment]
Met and agreed to adopt the `sb-c-inverted` syntax.
